# Homepage locators
readmore = "xpath://span[text()='Read More']"
architectpopup = "//span[text()='NO']/.."
email = "//input[@name='EMAIL']"
btnsubscribe = "//input[@name='subscribe']"
btncontinuebrowsing = "//p[text()='You successfully signed up to our newsletter.']/../..//a[text()='Continue browsing']"
btnconsentmain = "//button[@id='axeptio_main_button']"
acceptall = "//button[@id='axeptio_btn_acceptAll']"
myaccount = "(//a[contains(@href,'clubroom.theinvisiblecollection.com/my-account/')])[1]/span"
btnLogin = "//a[text()='Log in']"
username = "//input[@id='username']"
password = "//*[@id='password']"
logintoapp = "//button[@name='login']"

# ProductSearch locators
searchmenu = "//a[@class='search-pro-icon']"
search = "//input[@id='custom-search']"
srchbtn = "//input[@id='custom-search']/..//button"
img1="(//a[@class='vsz-product-container'])[1]"
addtocart="//button[@id='add-to-cart']"
cart11="//header[@id='header']//a[contains(@title,'Cart')]"
cart="(//a[@data-name='cart'])[1]"
opencart="//a[contains(text(),'Open My Cart')]"
proceed="//span[text()='Proceed to checkout']"
playlist="(//a[@class='play-list-icon'])[1]"
proceedchkout="//a[@title='Proceed to checkout']"

# Payment locators
firstname="//input[@id='billing_first_name']"
lastname="//input[@id='billing_last_name']"
email="//input[@id='billing_email']"
phone="//input[@id='billing_phone']"
streetaddress="//input[@id='billing_address_1']"
towncity="//input[@id='billing_city']"
pincode="//input[@id='billing_postcode']"
state="//label[@for='billing_state']/..//div"
stateselection1="//label[@for='billing_state']/..//div//div[@class='selectric-scroll']//li[text()=~]"
stateselection2="]'"
country="//label[@for='billing_country']/..//div[@class='selectric']"
countryselection1="//label[@for='billing_country']/..//div//div[@class='selectric-scroll']//li[text()=~]"
countryselection2="]'"
proceedtopay="//div[contains(text(),'Order Total')]/../../..//a[contains(text(),'Proceed to Payment')]"
county="//input[@id='billing_state']"
